using Microsoft.VisualBasic;
using Microsoft.VisualBasic.Compatibility;
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using TCBase;
using TCBase.clsRegistry;
using TCBase.clsSupport;
using TCBase.clsTrace;
[assembly: AssemblyTitle("TCWebLinks")]
//<Assembly: CLSCompliant(True)> 
[assembly: Guid("6BAAB2D8-96C1-4582-8E04-6B336D2929DC")]
