using Microsoft.VisualBasic;
using Microsoft.Win32;
using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using TCBase;
[assembly: AssemblyCompany("[Company]")]
[assembly: AssemblyCopyright("[Copyright]")]
[assembly: AssemblyDescription("[Description]")]
[assembly: AssemblyProduct("[ProductName]")]
[assembly: AssemblyTrademark("[ProductName]™")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("5.0.0.0")]
